apps/monitoramento/urls.py
from django.urls import path
from django.views.generic import TemplateView
from apps.monitoramento.views.monitoramento import FerramentaView
from apps.monitoramento.views.storage import ArmazenamentoView, NetappLisView, NetappModelView, TotalGrupoView, TotalStorageView, XE6QuotaListView, XE6QuotaView
from apps.monitoramento.views.uso import SupercomputadorHistView, SupercomputadorNodesView, SupercomputadorView
from apps.monitoramento.views.vm import XenPoolListView, XenPoolView, XenView

app_name = "monitoramento"

urlpatterns = [
    path("ferramentas/", FerramentaView.as_view(), name="ferramentas"),
    path("rnp/", TemplateView.as_view(template_name="monitoramento/rnp/rnp_home.html"), name="rnp_home"),
    
    path("xen/pool/", XenView.as_view(), name="vms_xen"),
    path("xen/pool/<int:pk>", XenPoolView.as_view(), name="vms_xen_pool"),
    path("xen/pool/<int:pk>/list/", XenPoolListView.as_view(), name="vms_xen_pool_list"),

    path("armazenamento/total/grupo/", TotalGrupoView.as_view(), name="storage_total_grupo"),
    path("armazenamento/total/storage/", TotalStorageView.as_view(), name="storage_total_storage"),

    path("armazenamento/", ArmazenamentoView.as_view(), name="storage"),
    path("netapp/<int:pk>/model/", NetappModelView.as_view(), name="storage_netapp_model"),
    path("netapp/<int:pk>/list/", NetappLisView.as_view(), name="storage_netapp_list"),

    path("xe6quota/", XE6QuotaView.as_view(), name="storage_xe6quota"),
    path("xe6quota/<int:pk>/list/", XE6QuotaListView.as_view(), name="storage_xe6quota_list"),
    
    path("supercomputador/", SupercomputadorView.as_view(), name="uso_supercomputador"),
    path("supercomputador/<int:pk>/nodes/", SupercomputadorNodesView.as_view(), name="uso_supercomputador_nodes"),
    path("supercomputador/<int:pk>/hist/", SupercomputadorHistView.as_view(), name="uso_supercomputador_hist"),
]

portal/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from apps.colaborador.views import PasswordResetConfirmView


urlpatterns = [
    path("", TemplateView.as_view(template_name="core/home.html"), name="home"),
    path("colaborador/", include("apps.colaborador.urls.noauth")),
    path("monitoramento/", include("apps.monitoramento.urls")),
    path("conta/", include("apps.colaborador.urls.auth")),
    path("admin/administrador/", include("apps.core.urls.auth")),
    path("estrutura/", include("apps.core.urls.noauth")),
    path("infra/", include("apps.infra.urls")),
    path("biblioteca/", include("apps.biblioteca.urls")),
    path("noc/", include("apps.noc.urls")),
    path("garb/", include("garb.urls")),
    path("conta/password_reset/", auth_views.PasswordResetView.as_view(html_email_template_name="registration/password_reset_email_html.html"), name="password_reset"),
    path("conta/reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('conta/', include('django.contrib.auth.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

apps/monitoramento/models/monitoramento.py
from django.db import models


class TipoMonitoramento(models.Model):
    nome = models.CharField("nome", max_length=255)

    class Meta:
        verbose_name = "Tipo"
        verbose_name_plural = "Tipos"
        ordering = ("nome",)

    def __str__(self):
        return self.nome


class Monitoramento(models.Model):
    TARGETS = (
        ("_blank", "nova aba"),
        (" ", "sem target"),
    )

    nome = models.CharField("nome", max_length=255)
    url = models.URLField("url")
    prioridade = models.IntegerField("prioridade")
    target = models.CharField("target", max_length=10, choices=TARGETS)
    tipo = models.ForeignKey('monitoramento.TipoMonitoramento', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Monitoramento"
        verbose_name_plural = "Monitoramentos"
        ordering = ("tipo", "prioridade", "nome")

    def __str__(self):
        return self.nome

apps/monitoramento/models/nagios.py
from apps.monitoramento.managers import NagiosServicosManager
from django.db import models


class NagiosServicos(models.Model):
    servico = models.CharField("Serviço", max_length=255)
    comando = models.CharField("comando Nagios", max_length=255)
    tempo = models.IntegerField("Tempo de verificação")
    padrao = models.BooleanField("Ativar por padrão", default=False)
    
    class Meta:
        verbose_name = "Nagios Serviço"
        verbose_name_plural = "Nagios Serviços"
        ordering = ("servico",)

    def __str__(self):
        return self.servico

    

apps/monitoramento/models/prometheus.py
from django.db import models


class Prometheus(models.Model):
    jobname = models.CharField("jobname", max_length=255)
    porta = models.IntegerField("porta")

    def __str__(self):
        return self.jobname

apps/monitoramento/views/monitoramento.py
from django.views.generic.base import TemplateView
from apps.monitoramento.models import TipoMonitoramento
from garb.views import ViewContextMixin

class FerramentaView(ViewContextMixin, TemplateView):
    template_name = "monitoramento/ferramentas/ferramentas.html"
    title = "Ferramentas"

    def get_context_data(self, **kwargs):
        context = super(FerramentaView, self).get_context_data(**kwargs)
        context["tipos_monitoramento"] = TipoMonitoramento.objects.all()
        return context

apps/monitoramento/views/storage.py
import math
from datetime import datetime, timedelta
import pandas as pd
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateView
from sklearn.linear_model import LinearRegression

from apps.core.models import Divisao, GrupoTrabalho
from apps.monitoramento.utils import Echarts, AxisData, AxisBase, Tooltip, Line, Grid
from apps.infra.models import Storage, StorageAreaGrupoTrabalho
from apps.monitoramento.models import (Area, QuotaUtilizada, StorageHistorico)
from garb.views import ViewContextMixin



class TotalStorageView(ViewContextMixin, TemplateView):
    template_name = "monitoramento/storage/total_storage.html"
    title = "TOTAL DE ARMAZENAMENTO POR STORAGE"

    def get_context_data(self, **kwargs):
        storages = Storage.objects.all()
        context = super(TotalStorageView, self).get_context_data(**kwargs)
        context["storages"] = storages
        return context

class TotalGrupoView(ViewContextMixin, TemplateView):
    template_name = "monitoramento/storage/total_grupo.html"
    title = "TOTAL DE ARMAZENAMENTO POR GRUPO DE TRABALHO"

    def get_context_data(self, **kwargs):
        grupos = GrupoTrabalho.objects.all()
        context = super(TotalGrupoView, self).get_context_data(**kwargs)
        context["grupos"] = grupos
        return context

class ArmazenamentoView(ViewContextMixin, TemplateView):
    template_name = "monitoramento/storage/armazenamento.html"
    title = "ARMAZENAMENTO"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        storages_das_areas = [divisao['storage_grupo_trabalho__storage_area__storage__id'] for divisao in Area.objects.distinct_id_storages()] 
        context["storages"] = Storage.objects.filter(pk__in=storages_das_areas)
        return context


class NetappModelView(TemplateView):
    template_name = "monitoramento/storage/netapp_model.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # consulta o Netapp Atenção no Id
        storage = get_object_or_404(Storage, id=kwargs["pk"])
        divisoes = []
        divisoes_das_areas = [divisao['storage_grupo_trabalho__grupo__divisao__id'] for divisao in Area.objects.distinct_id_divisoes()]
        # Lista as divisoes
        for divisao in Divisao.objects.filter(pk__in=divisoes_das_areas):
            # Consulta agregada na tabela de Areas buscando discos por divisao  filtrada pelo ID da divisao
            areas_divisao = Area.objects.aggregate_divisao_disco_sum().filter(storage_grupo_trabalho__grupo__divisao_id=divisao.id)[0]
            # Consulta agregada na tabela de StorageAreas buscando quota por divisao  filtrada pelo ID da divisao
            quota_divisao = StorageAreaGrupoTrabalho.objects.aggregate_divisao_quota_sum().filter(grupo__divisao_id=divisao.id, storage_area__storage_id=storage.id)[0]
            quota_total_kb = quota_divisao["quota__sum"] * 1024 * 1024 * 1024 * 1024
            area_total_usado_porcentagem = int((areas_divisao["disco_used__sum"] * 100) / quota_total_kb)
            area_total_liberado_porcentagem = int((areas_divisao["disco__sum"] * 100) / quota_total_kb) - area_total_usado_porcentagem
            divisoes.append(
                {
                    "obj": divisao,
                    "area_total_usado": areas_divisao["disco_used__sum"],
                    "area_total_liberado": areas_divisao["disco__sum"],
                    "quota_total": quota_total_kb,
                    "area_total_usado_porcentagem": area_total_usado_porcentagem,
                    "area_total_liberado_porcentagem": area_total_liberado_porcentagem,
                }
            )
        context["title"] = f'{storage.marca} {storage.modelo}'.upper()
        context["quotado"] = StorageAreaGrupoTrabalho.objects.aggregate_all_quota_sum().filter(storage_area__storage_id=storage.id)[0]["quota__sum"] * 1024 * 1024 * 1024 * 1024
        area_total = Area.objects.aggregate_all_snap_disco_used_deduplication_sum()
        context["reserva_utilizada"] = area_total["snap__sum"]
        context["liberado"] = area_total["disco__sum"]
        context["utilizado"] = area_total["disco_used__sum"]
        context["deduplicacao"] = area_total["deduplication__sum"]
        context["volumes"] = area_total["area__count"]
        context["divisoes"] = divisoes
        context["storage"] = storage
        return context


class NetappLisView(TemplateView):
    template_name = "monitoramento/storage/netapp_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        storage = get_object_or_404(Storage, id=4)
        grupo = get_object_or_404(GrupoTrabalho, id=kwargs["pk"])
        try:
            storage_area_grupo_trabalho = StorageAreaGrupoTrabalho.objects.get(storage_area__storage_id=storage.id, grupo_id=grupo.id)
            try:
                combined_alerts = Area.objects.filter((Q(porcentagem_disco_used__gte=95) | Q(snapshot_size_used__gte=95)), storage_grupo_trabalho_id=storage_area_grupo_trabalho.id)
                total_areas = Area.objects.aggregate_grupo_disco_sum().filter(storage_grupo_trabalho_id=storage_area_grupo_trabalho.id)[0]
                storage_area_grupo_trabalho.area_total_usado = int(total_areas["disco_used__sum"])
                storage_area_grupo_trabalho.area_total_liberado = int(total_areas["disco__sum"])
                pandas_df_areahistorico_grupo_30d = pd.DataFrame(
                    list(StorageHistorico.objects.aggregate_grupo_historico_disco_sum().filter(storage_grupo_trabalho_id=storage_area_grupo_trabalho.id, atualizacao__gte=datetime.now()  - timedelta(days=30)))
                )
                context["storage_area_grupo_trabalho_previsao_30d"] = self.get_previsao_30d(pandas_df_areahistorico_grupo_30d)
                context["storage_area_grupo_trabalho_grafico_historico"] = self.get_grafico_historico(pandas_df_areahistorico_grupo_30d)
                context["combined_alerts"] = len(combined_alerts)
            except IndexError:
                storage_area_grupo_trabalho.area_total_usado = 0
                storage_area_grupo_trabalho.area_total_liberado = 0
        except ObjectDoesNotExist:
            storage_area_grupo_trabalho = StorageAreaGrupoTrabalho()
            storage_area_grupo_trabalho.grupo = grupo
            storage_area_grupo_trabalho.area_total_usado = 0
            storage_area_grupo_trabalho.area_total_liberado = 0
        context["title"] = grupo.grupo
        context["storage_area_grupo_trabalho"] = storage_area_grupo_trabalho
        return context

    def get_grafico_historico(self, df_area_historico):
        size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
        # iniciliza configuracoes do matplotlib
        # Define tamanho para legenda
        size_indice = df_area_historico.disco_used__avg.max()
        size = size_name[int(math.floor(math.log(size_indice, 1024)))]
        # Transformas os tamanhos de KB para tamanho Human
        df_area_historico["disco_used__avg"] = df_area_historico.disco_used__avg.apply(lambda x: round(int(x) / float(math.pow(1024, int(math.floor(math.log(size_indice, 1024))))), 2))
        # Cria Eixo X dos Ultimos 30 dias
        dti = pd.DataFrame({"atualizacao": pd.date_range((datetime.now() - timedelta(days=30)).strftime("%Y-%m-%d"), periods=30, freq="D")})
        # Merge dos date + data
        serie = pd.merge_ordered(dti, df_area_historico).dropna()

        grafico = Echarts()
        grafico.set_color(["#0277bd"])
        x_axis = AxisData("category", "bottom", [x.strftime("%d/%m") for x in pd.to_datetime(serie["atualizacao"], format="T")])
        x_axis.set_axis_label({"rotate": 45, "textStyle": {"fontSize": 8}})
        grafico.add_x_axis(x_axis)
        y_axis = AxisBase("value")
        y_axis.set_min((serie["disco_used__avg"]).min() - 0.01)
        y_axis.set_max((serie["disco_used__avg"]).max() + 0.01)
        grafico.add_y_axis(y_axis)
        grafico.add_series(Line("Utilizado %s" % size, (serie["disco_used__avg"]).tolist()))
        grafico.set_tooltip(Tooltip())
        grafico.set_grid(Grid())
        return grafico

    def get_previsao_30d(self, df_area_historico):
        model = LinearRegression()
        X = df_area_historico.atualizacao.apply(lambda x: x.toordinal()).values.reshape(-1, 1)
        y = df_area_historico.disco_used__avg.values.reshape(-1, 1)
        model.fit(X, y)
        futuro = (datetime.now() + timedelta(days=30)).toordinal()
        return  model.predict([[futuro]])


class XE6QuotaView(TemplateView):
    template_name = "monitoramento/storage/xe6_quota.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # consulta o Netapp Atenção no Id
        storage = get_object_or_404(Storage, id=5)
        # Consulta agregada na tabela de StorageAreas buscando quota por divisao  filtrada pelo ID da divisao
        storage_area_grupo_trabalhos = StorageAreaGrupoTrabalho.objects.filter(storage_area__storage_id=storage.id)
        grupos = [x.grupo for x in storage_area_grupo_trabalhos]
        context["title"] = "XE6 Quota"
        context["grupos"] = sorted(grupos, key=lambda x: (x.divisao.divisao, x.grupo))
        context["storage"] = storage
        total_quota_storage = QuotaUtilizada.objects.aggregate_all_quotado_used_sum()
        context["quotado"] = total_quota_storage["quota__sum"]
        context["utilizado"] = total_quota_storage["usado__sum"]
        context["quotas"] = total_quota_storage["id__count"]
        return context


class XE6QuotaListView(TemplateView):
    template_name = "monitoramento/storage/xe6_quota_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        storage = get_object_or_404(Storage, id=5)

apps/monitoramento/views/vm.py
from django.views.generic import TemplateView
from apps.monitoramento.utils.xen import XenInfo
from apps.infra.models import AmbienteVirtual
from garb.views import ViewContextMixin


class XenView(ViewContextMixin, TemplateView):
    template_name = "monitoramento/vm/xen.html"
    title = "Ambiente Virtual"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ambientes = AmbienteVirtual.objects.all()
        context["ambientes"] = ambientes
        return context


class XenPoolView(TemplateView):
    template_name = "monitoramento/vm/xen_pool.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ambiente = AmbienteVirtual.objects.get(pk=kwargs["pk"])
        context["title"] = str(ambiente)
        context["ambiente"] = ambiente
        return context


class XenPoolListView(TemplateView):
    template_name = "monitoramento/vm/xen_pool_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ambiente = AmbienteVirtual.objects.get(pk=kwargs["pk"])
        servidores = [servidor.nome for servidor in ambiente.servidor.all()]
        xen_info = XenInfo(str(ambiente), servidores)
        context["title"] = ambiente
        context["pool"] = xen_info.carregar()
        return context

apps/monitoramento/templates/monitoramento/uso/supercomputador.html
{% extends "admin/base.html" %}
{% load static %}
{% load templatetags %}
{% load i18n %}

{% block extrastyle %}
    <link href="{% static 'monitoramento/css/uso.css' %}" type="text/css" rel="stylesheet" />
{% endblock %}


{% block content %}
<div id="content-main">
    <div id='view_uso'>
        {% for supercomputador in supercomputadores %}
        <div class="d-flex row p-0 m-0 ">
            <div class="box-garb m-0 p-0 col-12">
                <div class="card-header p-0 text-center border-bottom-0 bg_cor_primaria white-text card-grupo-header">
                    <h5 class="card-title p-2 m-0"><b>{{supercomputador}}</b></h5>
                </div>
                <div class="card-body black-text bg_cor_primaria m-0 p-0 ">
                    <div class="card-text m-0 ml-2 p-2 white row ">
                        <div class="col-6 p-0 mt-1" id="super_{{ supercomputador.id }}_hist"></div>
                        <div class="col-6 p-0 pr-1" id="super_{{ supercomputador.id }}_rack"></div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        {% endfor %}
        <div class="box-garb">
            <div class="d-flex row ">
                <div class="col text-right">
                    Legenda:
                </div>
                <div class="col rack node legenda free_batch pb-1">
                    free node
                </div>
                <div class="col rack node legenda service  pb-1 ">
                    service node
                </div>
                <div class="col rack node legenda  pb-1">
                    processing node
                </div>
                <div class="col rack node legenda waiting   pb-1">
                    waiting node
                </div>
                <div class="col rack node legenda allocated_interactive  pb-1">
                    allocated
                </div>
                <div class="col  rack node legenda suspect  pb-1">
                    suspect node
                </div>
                <div class="col  rack node legenda down  pb-1">
                    down node
                </div>
                <div class="col  rack node legenda noexist  pb-1">
                    nonexistent node
                </div>
                <div class="col ">
                <button type="button" class="button float-right" id="view_monitoramento" data-name="view_uso">
                    <i class="fa fa-eye fa-lg p-1"></i>
                </button>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extrajs %}
    <script src="{% static 'js/garb_page_wide.js' %}"></script>
    <script>
        function load() {
            {% for supercomputador in supercomputadores %}
                $("#super_{{ supercomputador.id }}_rack").load("{% url 'monitoramento:uso_supercomputador_nodes' pk=supercomputador.id  %}");
                $("#super_{{ supercomputador.id }}_hist").load("{% url 'monitoramento:uso_supercomputador_hist' pk=supercomputador.id %}");
            {% endfor %}
        }
        load();
        setInterval(function () { load() }, 180000);
        setInterval(function () { window.location.reload(); }, 6000000);
    </script>
{% endblock %}

apps/monitoramento/templates/monitoramento/uso/supercomputador_hist.html
{% load static %}
{% load templatetags %}
{% if numero %}
    <div class="row p-0 m-0">
        <div class="col-12 p-1">
            <div id="grafico_{{supercomputador.id}}" style="width: 100%; height: 259px"> </div>
        </div>
        <div class="col-3 p-1">
            <div class="card shadow-menu border-0">
                <div class="card-body black-text green {{ numero.get_alerta.0 }} m-0 p-0 card-grupo-numero ">
                    <div class="card-text ml-2 mt-1px mr-1px mb-1px pl-3 pt-1 green {{ numero.get_alerta.1 }} lighten-2 card-grupo-data">
                        running node: <b> <h1 class="text-center p-2">{{ numero.get_used }}</h1> </b>
                    </div>
                </div>
                <div class="card-body p-0 m-0 text-left green {{ numero.get_alerta.0 }} white-text card-grupo-numero">
                    <div class="card-text ml-2 mr-1px mb-1px pl-3 pt-0 pb-1 green {{ numero.get_alerta.0 }} card-grupo-data-d">
                        use nodes: <b> {{ numero.get_used_percent|floatformat:0 }}%</b>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3 p-1">
            <div class="card shadow-menu border-0">
                <div class="card-body black-text alerta {{ numero.get_alerta.2 }} darken-4 m-0 p-0 card-grupo-numero ">
                    <div class="card-text ml-2 mt-1px mr-1px mb-1px pl-3 pt-1 {{ numero.get_alerta.2 }} lighten-2 card-grupo-data">
                        down node: <b> <h1 class="text-center p-2">{{ numero.get_downs }}</h1>  </b>
                    </div>
                </div>
                <div class="card-body p-0 m-0 text-left {{ numero.get_alerta.2 }} darken-4 white-text card-grupo-numero">
                    <div class="card-text ml-2 mr-1px mb-1px pl-3 pt-0 pb-1 {{ numero.get_alerta.2 }}  darken-4 card-grupo-data-d">
                        off nodes: <b> {{ numero.get_down_percent|floatformat:0 }}%</b>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3 p-1">
            <div class="card shadow-menu border-0">
                <div class="card-body black-text orange {{ numero.get_alerta.0 }} m-0 p-0 card-grupo-numero ">
                    <div class="card-text ml-2 mt-1px mr-1px mb-1px pl-3 pt-1 orange {{ numero.get_alerta.1 }} lighten-2 card-grupo-data">
                        free nodes: <b> <h1 class="text-center p-2">{{ numero.get_frees }}</h1> </b>
                    </div>
                </div>
                <div class="card-body p-0 m-0 text-left orange {{ numero.get_alerta.0 }} white-text card-grupo-numero">
                    <div class="card-text ml-2 mr-1px mb-1px pl-3 pt-0 pb-1 orange {{ numero.get_alerta.0 }} card-grupo-data-d">
                        service node: <b>{{ numero.get_services }}</b>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3 p-1">
            <div class="card shadow-menu border-0 mb-2">
                <div class="card-body black-text blue-grey darken-4 m-0 p-0 card-grupo-numero ">
                    <div class="card-text ml-2 mt-1px mr-1px mb-1px pl-3 pt-1 blue-grey lighten-2 card-grupo-data">
                        <p class="pt-1 pb-2 mb-1"> jobs running:<b> {{ numero.jobs }}</b></p>
                    </div>
                </div>
            </div>
            <div class="card shadow-menu border-0 mb-2">
                <div class="card-body black-text {{ numero.get_alerta_time }} darken-4 m-0 p-0 c card-update">
                    <div class="card-text ml-2 mt-1px mr-1px mb-1px pl-3 pt-1  {{ numero.get_alerta_time }} lighten-2  card-update">
                        <p class="pt-1 pb-2 mb-1"> update:<b> {{ numero.get_last }}</b></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'js/echarts.min.js' %}"></script>
    <script type="text/javascript">
        var chart = echarts.init(document.getElementById("grafico_{{supercomputador.id}}"));
        chart.setOption({{ grafico.export | safe | echart_safe }});
    </script>
{% endif %}

apps/monitoramento/templates/monitoramento/uso/supercomputador_nodes.html
{% load templatetags %}
<div class="row p-0 pt-2 m-0">
    {% for rack in supercomputador.racks %}
        <div class="col-3 p-1">
            <div class="card shadow-menu border-0">
                <div class="card-header p-0 text-center blue-grey darken-2 white-text rounded-0">
                    <h6 class="card-title p-1 m-0"><b>{{ supercomputador.modelo }} {{ rack }}</b></h6>
                </div>
                <div class="card-body m-0 blue-grey darken-2 ">
                    <div class="white p-0 m-0 ">
                        <div class="card-text card-grupo-data
                            {% if forloop.revcounter == 0 or forloop.revcounter == 4 %}  tooltipleft
                            {% elif forloop.revcounter == 2 or  forloop.revcounter == 6  or  forloop.revcounter == 14 %} tooltipright
                            {% else %} tooltiptop {% endif %}">
                            {% for no in rack.nos %}
                                <div class="rack node {{no.get_classe_html}} {{no.usuario|to_replace_dot}} "
                                    {% if  no.usuario  %} 
                                        data-toggle="tooltip" data-html="true" title="User: <b>{{no.usuario}}</b><br>Number of Nodes: <b>{{no.size}}</b><br>Running for: <b>{{no.tempo}}</b><br>Script: <b>{{no.comando}}</b><br>Position: <b>{{no}}" 
                                    {% else %}
                                        {% if no.get_classe_html != 'noexist' %}
                                            data-toggle="tooltip" data-html="true" title="<p> Position: <b>{{no}}</b></p>" 
                                        {% endif%}
                                    {% endif %}
                                    >
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <div class="row">
            <h1 class="display-4 text-danger p-5"> ERRO!!</h1>
        </div>
    {% endfor %}
</div>
<div class="col-12 p-1 m-0">
    {% for user in users %}
        <span class="badge badge-info m-1 p-1 shadow-sm" id='{{ user|to_replace_dot }} '>{{ user }}</span>
    {% endfor %}
</div>

<script>
    $(".badge").on("mouseover", function () {
        classe = $(this).attr('id')
        $(".node").css({ opacity: 0.3 });
        $("." + classe).css({ opacity: 1 });
    }).on("mouseout", function () {
        $(".node").css({ opacity: 1 });
    });

    $(function () {
        $('[data-toggle="tooltip"]').tooltip({ boundary: 'window' })
    })
</script>