portal/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from apps.colaborador.views import PasswordResetConfirmView


urlpatterns = [
    path("", TemplateView.as_view(template_name="core/home.html"), name="home"),
    path("colaborador/", include("apps.colaborador.urls.noauth")),
    path("monitoramento/", include("apps.monitoramento.urls")),
    path("conta/", include("apps.colaborador.urls.auth")),
    path("admin/administrador/", include("apps.core.urls.auth")),
    path("estrutura/", include("apps.core.urls.noauth")),
    path("infra/", include("apps.infra.urls")),
    path("biblioteca/", include("apps.biblioteca.urls")),
    path("noc/", include("apps.noc.urls")),
    path("garb/", include("garb.urls")),
    path("conta/password_reset/", auth_views.PasswordResetView.as_view(html_email_template_name="registration/password_reset_email_html.html"), name="password_reset"),
    path("conta/reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('conta/', include('django.contrib.auth.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

apps/colaborador/models.py
from datetime import datetime, timedelta, date
import re
from unicodedata import normalize
from django.contrib.auth.models import AbstractUser
from django.db import models
from apps.core.models import GrupoPortal


class Vinculo(models.Model):
    vinculo = models.CharField("vínculo", max_length=255)

    class Meta:
        ordering = ["vinculo"]
        verbose_name = "Vínculo"
        verbose_name_plural = "Vínculos"

    def __str__(self):
        return self.vinculo


class Colaborador(AbstractUser):
    telefone = models.CharField("telefone", max_length=255)
    data_nascimento = models.DateField("Data de Nascimento", max_length=255)
    documento = models.CharField("Documento", max_length=255)
    documento_tipo = models.CharField("Tipo Documento", max_length=255)
    cpf = models.CharField("CPF", max_length=255, blank=True, null=True)
    predio = models.ForeignKey("core.Predio", verbose_name="Prédio", null=True, blank=True, on_delete=models.PROTECT)
    data_inicio = models.DateField("Data de Início")
    data_fim = models.DateField("Data de Fim", null=True, blank=True)
    ramal = models.CharField("Ramal", max_length=255, null=True, blank=True)
    empresa = models.CharField("Empresa Terceirizada", max_length=255, blank=True, null=True)
    registro_inpe = models.CharField("Matrícula SIAPE", max_length=255, null=True, blank=True)
    externo = models.BooleanField("Usuário Externo", default=False)
    uid = models.IntegerField("UID", default=0)
    is_active = models.BooleanField('ativo', default=False)
    vinculo = models.ForeignKey("colaborador.Vinculo", verbose_name="vínculo", on_delete=models.PROTECT)
    divisao = models.ForeignKey('core.Divisao', verbose_name="Divisão | Coordenação", on_delete=models.PROTECT)
    responsavel = models.ForeignKey("self", null=True, blank=True, verbose_name="Responsavel", related_name="responsavel_user", on_delete=models.PROTECT)
    
    class Meta:
        ordering = ["username"]
        verbose_name = "Colaborador"
        verbose_name_plural = "Colaboradores"
        permissions = (
            ("responsavel_colaborador", "Responsável pode aprovar acesso colaborador"),
            ("secretaria_colaborador", "Secretaria pode revisar colaborador"),
            ("suporte_colaborador", "Suporte pode criar o colaborador"),
            ("chefia_colaborador", "Chefia por aprovar colaborador"),
        )

    def __create_user_name(self, name, id_last_name=1):
        nome_corrigido = re.sub(r"\ d[aeiou]\ ", " ", normalize("NFKD", name).encode("ASCII", "ignore").decode("ASCII")).split(" ")
        username = nome_corrigido[0] + "." + nome_corrigido[id_last_name * -1]
        if id_last_name == len(nome_corrigido):
            return nome_corrigido[0] + "." + nome_corrigido[-1] + "_"
        if Colaborador.objects.filter(username=username.lower()).exists():
            id_last_name += 1
            username = self.__create_user_name(name, id_last_name)
        return username

    def __set_user_name(self):
        name = f"{self.first_name} {self.last_name}"
        # Verifica Email do INPE
        if "@inpe.br" in self.email:
            return self.email.replace("@inpe.br", "").lower()
        return self.__create_user_name(name).lower()

    def get_documento_principal(self):
        if self.cpf is None:
            return f"{self.documento_tipo}: <b>{self.documento}</b>"
        return f"CPF: <b>{self.cpf}</b>"

    def clean(self):
        from django.core.exceptions import ValidationError
        if not self.username:
            self.username = self.__set_user_name()
        if Colaborador.objects.filter(username=self.username).exclude(id=self.pk).exists():
            raise ValidationError({"email": ("Username já existe")})
        if Colaborador.objects.filter(email=self.email).exclude(id=self.pk).exists():
            raise ValidationError({"email": ("Email já existe")})
        super().clean()

    def chefia_aprovar(self):
        self.is_staff = True
        self.save()

    def suporte_criar(self):
        self.is_active = True
        self.groups.add(GrupoPortal.objects.get(name="Colaborador"))
        self.save()

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class VPN(models.Model):
    recurso = models.CharField('Recurso a ser acessado', max_length=255 )
    data_solicitacao = models.DateField('Data da solicitação', auto_now_add=True, null=True, blank=True)
    data_abertura = models.DateField('Data da Abertura', null=True, blank=True)
    data_validade = models.DateField('Data Validade', null=True, blank=True)
    mac_cabeado = models.CharField('MAC Address Cabeado', max_length=255 ,null=True, blank=True)
    mac_wifi = models.CharField('MAC Address Wireless', max_length=255, null=True, blank=True)
    justificativa = models.CharField('Justificativa', max_length=255 )
    status = models.CharField('Status', default='Solicitada', max_length=255, null=True, blank=True)
    local =  models.CharField('Local de trabalho',  max_length=255, null=True, blank=True)
    colaborador = models.ForeignKey("colaborador.Colaborador", verbose_name="Colaborador", on_delete=models.PROTECT)
    class Meta :
        ordering = ['-data_validade']
        verbose_name = "VPN"
        verbose_name_plural = "VPNs"

    def __str__(self):
        recurso = self.recurso.split(" | ")
        return f"{self.colaborador.username} | {recurso[0]}"

    @property
    def data_fim_vpn(self):
        if self.data_validade:
            if self.data_validade <= datetime.now() + timedelta(days=365):
                return self.data_validade
        else:
            return datetime.now() + timedelta(days=365)

    @property
    def get_mac_cabeado(self):
        if self.mac_cabeado: 
            return self.mac_cabeado
        else:
            return  "___:___:___:___:___"

    @property
    def get_mac_wifi(self):
        if self.mac_wifi: 
            return self.mac_wifi
        else:
            return  "___:___:___:___:___"

    @property
    def get_local(self):
        if self.local: 
            return self.local
        else:
            return  "________________________________"

    @property
    def status_atualizado(self):
        if self.data_validade  < date.today():
            return "Vencida"
        elif self.data_validade > date.today() - timedelta(days=30) :
            return "Vai vencer"
        else:
            return self.status

apps/core/forms.py
from django import forms
from django.db.models import Q
from django.forms.models import ModelChoiceField

from apps.colaborador.models import Colaborador
from apps.core.models import Divisao, GrupoTrabalho, ResponsavelGrupoTrabalho
from django.core.exceptions import ValidationError


class UserChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return f"{obj.first_name} {obj.last_name} | {obj.email}"


class DivisaoChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return f"{obj.divisao} - {obj.divisao_completo}"

class GrupoTrabalhoForm(forms.ModelForm):
    share = forms.BooleanField(required=False)
    operacional = forms.BooleanField(required=False, label="Operacional")
    desenvolvimento = forms.BooleanField(required=False, label="Desenvolvimento")
    pesquisa = forms.BooleanField(required=False, label="Pesquisa")
    documento = forms.BooleanField(required=False, label="Documento")
    divisao = DivisaoChoiceField(queryset=Divisao.objects.all(), label="Divisão")

    class Meta:
        model = GrupoTrabalho
        fields = "__all__"


class ResponsavelGrupoTrabalhoInLineForm(forms.ModelForm):
    responsavel = forms.ModelChoiceField(queryset=Colaborador.objects.filter(is_staff=True, groups__name="Responsavel").distinct(), label="Responsável", widget=forms.Select(attrs={"data-live-search": "True"}))

    class Meta:
        model = ResponsavelGrupoTrabalho
        fields = ("responsavel",)


class DivisaoForm(forms.ModelForm):
    chefe = UserChoiceField(queryset=Colaborador.objects.filter(is_staff=True, groups__name="Chefia da Divisão").distinct(), required=True)
    chefe_substituto = UserChoiceField(queryset=Colaborador.objects.filter(is_staff=True, groups__name="Chefia da Divisão").distinct(), required=True)

    chefe_ativo = forms.BooleanField(required=False, label="Chefe Ativo")
    chefe_substituto_ativo = forms.BooleanField(required=False, label="Chefe Substituto Ativo")
    email = forms.EmailField(required=True, label="Email Secretaria")

    class Meta:
        model = Divisao
        fields = ['divisao', 'divisao_completo', 'email', 'coordenacao', 'chefe', 'chefe_ativo','chefe_substituto', 'chefe_substituto_ativo']

    def clean_chefe_ativo(self):
        chefe_substituto_ativo = False
        chefe_ativo = self.cleaned_data.get("chefe_ativo")
        if 'chefe_substituto_ativo' in self.data.keys():
            chefe_substituto_ativo = self.data['chefe_substituto_ativo']
        if ( not chefe_ativo and not chefe_substituto_ativo):
            raise ValidationError("Precisa ter um chefe ativo")
        return chefe_ativo

    def clean_chefe_substituto_ativo(self):
        chefe_ativo = self.cleaned_data.get("chefe_ativo")
        chefe_substituto_ativo = self.cleaned_data.get("chefe_substituto_ativo")
        if ( not chefe_ativo and not chefe_substituto_ativo):
            raise ValidationError("Precisa ter um chefe ativo")
        return chefe_substituto_ativo

apps/colaborador/templates/colaborador/chefia.html
{% extends "base.html" %}
{% load i18n  garb_tags %}

{% block content %}
    <div class="module-box">
        <div class="content-box">
                <div class="title">
                    <h2 class="m-0  text-center">{{ None|garb_title }} / COIDS / INPE</h2>
                </div>
                <div class="text text-center p-4">
                {% if validlink %}
                    <p class="msg text-center ">O Colaborador <b>{{ colaborador.full_name}}</b> foi <b class="text-success">APROVADO COM SUCESSO</b>.</p>
                    <p class="msg text-center "> Obrigado.</p>
                    <br>
                {% else %}
                    <p class="msg text-center ">O Colaborador j&aacute; foi aprovado ou aconteceu algum <b>problema</b> com o cadastro, solicite para secretaria enviar a revisão novamente</p>
                    <p> Obrigado.</p>
                    <br>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

apps/colaborador/templates/colaborador/externo.html
{% extends "admin/base.html" %}
{% load static %}
{% load garb_form %}

{% block content %}
    <form method="post" id="formValidate" action="{% url 'colaborador:externo' %}">
        {% csrf_token %}
        {{ form|render }}
        <div id="content-main">
            <div class="change-columns">
                <div class="main-column">
                    <div class="box-garb module aligned {{ fieldset.classes }} text-right pr-5">
                        <button type="submit" class="btn btn-primary width-btn-min ">Enviar Email</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

apps/colaborador/templates/colaborador/secretaria.html
{% extends "admin/base.html" %}
{% load static i18n %}

{% block content %}
<div id="content-main">
	<div class="change-columns">
		<div class="main-column">
			<div class="box-garb">
				<div class="module-header">
					<div class="legend">Aprova&ccedil;&atilde;o de novos colaboradores da <b
							class="text-danger">{{divisao.full_name}} </b></div>
				</div>
				<p>Voc&ecirc; &eacute; respon&aacutevel por um importante controle dentro do INPE</p>
				<p class="text-justify">Voc&ecirc; pode acessar nessa p&aacute;gina os Termos de compromissos
					necess&aacute;rios para
					regulamenta&ccedil;&atilde;o do novo colaborador do INPE, as informa&ccedil;&otilde;es contidas no
					cadastro devem ser conferidas e os respectivos termos/formul&aacute;rios impressos e das assinados.
				</p>
				<p>Com TUDO OK, voc&ecirc; pode <b class="text-success">ENVIAR REVIS&Atilde;O</b> do cadastro para o
					Chefe da Divis&atilde;o <b class="text-success">AUTORIZAR</b> , se N&Atilde;O estiver correto
					e/ou sem assinaturas &eacute; s&oacute; <b class="text-danger">NEGAR</b>
				</p>
				<p> <small>*O email com link para revis&atilde;o dura 24h</small></p>
				<p class="text-danger pt-3"><b>Chefe(s) Ativo(s)</b></p>
				{% if divisao.chefe_ativo %}
				<p> - {{ divisao.chefe.first_name}} {{ divisao.chefe.last_name}} | {{divisao.chefe.email}}</p>
				{% endif %}
				{% if divisao.chefe_substituto_ativo %}
				<p> - {{ divisao.chefe_substituto.first_name}} {{ divisao.chefe_substituto.last_name}} |
					{{divisao.chefe_substituto.email}}</p>
				{% endif %}
			</div>
			{% if divisao.chefe_ativo or divisao.chefe_substituto_ativo  %}
			{% for colaborador in colaboradores %}
			<div class="box-garb">
				<div id="accordion" role="tablist" aria-multiselectable="true">
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="heading{{ colaborador.id }}">
							<div class="module-header">
								<a role="button" class="collapsed" data-toggle="collapse" data-parent="#accordion"
									href="#collapse{{ colaborador.id }}" aria-expanded="false"
									aria-controls="collapse{{ colaborador.id }}">
									<div class="legend">{{ colaborador.full_name|upper  }}</div>
								</a>
							</div>
						</div>
						<div id="collapse{{ colaborador.id }}" class="panel-collapse collapse in" role="tabpanel"
							aria-labelledby="heading{{ colaborador.id }}">
							<div class="panel-body">
								<div class="row">
									<legend class="txt_cor_primaria">Informa&ccedil;&otilde;es Pessoais</legend>
									<div class="col-sm-5 offset-1">
										<div>
											<p><b>Nome: </b>{{ colaborador.full_name }}</p>
										</div>
										<div>
											<p><b>Data Nascimento: </b> {{ colaborador.data_nascimento }}</p>
										</div>
										
										{% if colaborador.cpf %}
										<div>
											<p><b>CPF: </b> {{ colaborador.cpf }}</p>
										</div>
										{% endif %}
									</div>
									<div class="col-sm-5">
										<div>
											<p><b>Email: </b>{{ colaborador.email }}</p>
										</div>
										<div>
											<p><b>Telefone: </b> {{ colaborador.telefone }}</p>
										</div>
										<div>
											<p><b>{{ colaborador.documento_tipo }} : </b> {{ colaborador.documento}}</p>
										</div>
									</div>
								</div>
								<div class="row pr-2 pl-2">
									<legend  class="txt_cor_primaria">Informa&ccedil;&otilde;es Profissionais</legend>
									<div class="col-sm-10 offset-1">
										<div>
											<p class="mb-0"><b>Divis&atilde;o | Coordena&ccedil;&atilde;o: </b> {{ colaborador.divisao.full_name }}</p>
										</div>
									</div>
									<div class="col-sm-5 offset-1">
										<div>
											<p class="mb-0"><b>V&iacute;nculo: </b>{{ colaborador.vinculo }}</p>
										</div>
									</div>
									<div class="col-sm-5">
										<div>
											<p class="mb-0"><b>Colaborador Externo: </b>
												{% if colaborador.externo %}
													<img src="{% static "admin/img/icon-yes.svg" %}">
												{% else %}
													<img src="{% static "admin/img/icon-no.svg" %}">
												{% endif %}
											</p>
										</div>
									</div>
									
									<div class="col-sm-5 offset-1">
										<div>
											<p><b>Data de In&iacute;cio: </b>{{ colaborador.data_inicio|date:"SHORT_DATE_FORMAT" }}</p>
										</div>
										{% if not colaborador.externo %}
											<div>
												<p><b>Ramal: </b>{{ colaborador.ramal }}</p>
											</div>
										{% endif %}
										{% if colaborador.responsavel %}
											<div>
												<p><b>Respons&aacute;vel: </b>{{ colaborador.responsavel }}</p>
											</div>
										{% endif %}
									</div>
									<div class="col-sm-5  mt-0">
										{% if colaborador.vinculo.vinculo != 'Administrador' %}
											{% if colaborador.vinculo.vinculo == 'Servidor' %}
												<div>
													<p><b>Matr&iacute;cula SIAPE: </b>{{ colaborador.registro_inpe }}</p>
												</div>
											{% else %}
												<div>
													<p><b>Data de Fim: </b>{{ colaborador.data_fim|date:"SHORT_DATE_FORMAT" }}</p>
												</div>
											{% endif %}
										{% endif %}
										{% if not colaborador.externo %}
											<div>
												<p><b>Pr&eacute;dio: </b>{{ colaborador.predio }}</p>
											</div>
										{% endif %}
										
										{% if colaborador.vinculo.vinculo == 'Terceiro' %}
										<div>
											<p><b>Empresa Terceirizada: </b>{{ colaborador.empresa }}</p>
										</div>
										{% endif %}
									</div>
								</div>
								<div class="module-footer">
									<div class="buttons">
										<a href="{% url 'colaborador:secretaria_termo' colaborador.id  %}">
											<button type="button" class="btn btn-secondary width-btn-min">Ver termo de
												compromisso</button>
										</a>
										<button type="button" class="btn btn-danger width-btn-min negar"
											data-toggle="modal" data-target=".modal" value="{{colaborador.id}}">
											Negar
										</button>
										<a href="{% url 'colaborador:secretaria_revisar' colaborador.id %}">
											<button type="submit" class="btn btn-success width-btn-min aprovar"
												value="{{colaborador.id}}">Enviar revis&atilde;o</button>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% empty %}
			<div class="box-garb">
				<p>N&atilde;o existe colaborador para ser revisado.</p>
			</div>
			{% endfor %}
			{% else %}
			<div class="box-garb">
				<p>Precisa ter um chefe ativo para aprovar colaboradores</p>
			</div>
			{% endif %}
		</div>
		<div class="box-column box-garb">
			<div class="module-header">
				<div class="legend">Colaboradores</div>
			</div>
			<div id="status"></div>
		</div>
	</div>
</div>
<div class="modal" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header alert-danger">
				<h5 class="modal-title">Ops!!! tem algo errado, negar o cadastro. </h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form method="post" id="formValidate" action="{% url 'colaborador:secretaria_negar' %}">
				<div class="modal-body">
					{% csrf_token %}
					{{  form_negar }}
					<br>
					<div class="module-footer">
						<div class="buttons">
							<button type="submit" class="btn btn-danger width-btn-min">Negar</button>
							<button type="button" class="btn btn-secondary width-btn-min"
								data-dismiss="modal">Cancelar</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

{% block extrajs %}
<script>
	$(".negar").click(function () {
		$("#id_motivo").val("");
		$("#id_colaborador").attr('value', $(this).val());
	});
	$("#status").load("{% url 'colaborador:status' %}");
	setInterval(function () { window.location.reload(); }, 60000);
</script>
{% endblock %}

apps/colaborador/templates/colaborador/suporte.html
{% extends "admin/base.html" %}
{% load static i18n %}

{% block content %}
<div id="content-main">
	<div class="change-columns">
		<div class="main-column">
			<div class="box-garb">
				<div class="module-header">
					<div class="legend">Cria&ccedil;&atilde;o de novos colaboradores</div>
				</div>
				<p>Voc&ecirc; &eacute; respon&aacute;vel por um importante controle dentro do CPTEC/INPE</p>
				<p>Fique atento ao UID se for <b>atualiza&ccedil;&atilde;o</b> tem que consultar o UID na planilha</p>
				<p>Fique atento para <b>novas contas</b>, pois &eacute; necess&aacute;rio confirma&ccedil;&atildeo da
					login com SCTI.</p>
			</div>
			{% for colaborador in colaboradores %}
			<div class="box-garb">
				<div id="accordion" role="tablist" aria-multiselectable="true">
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="heading{{ colaborador.id }}">
							<div class="module-header">
								<a role="button" class="collapsed" data-toggle="collapse" data-parent="#accordion"
									href="#collapse{{ colaborador.id }}" aria-expanded="false"
									aria-controls="collapse{{ colaborador.id }}">
									<div class="legend">{{ colaborador.full_name|upper  }}</div>
								</a>
							</div>
						</div>
						<div id="collapse{{ colaborador.id }}" class="panel-collapse collapse in" role="tabpanel"
							aria-labelledby="heading{{ colaborador.id }}">
							<div class="panel-body">
								<div class="row pr-2 pl-2">
									<legend class="txt_cor_primaria legend">Informa&ccedil;&otilde;es da Conta</legend>
									<div class="col-sm-5 offset-1">
										<div>
											<p><b class="font-weight-bold">Solicitante: </b>{{ colaborador.full_name }}
											</p>
										</div>
										<div>
											<p><b>Usu&aacute;rio: </b>{{ colaborador.username }}</p>
										</div>
									</div>
									<div class="col-sm-5 ">
										<div>
											<p><b class="font-weight-bold">Email: </b>{{ colaborador.email }}</p>
										</div>
										<div>
											<p><b>Uid: </b>{{ colaborador.uid }}</p>
										</div>
									</div>
								</div>
								<div class="row pr-2 pl-2">
									<legend  class="txt_cor_primaria">Informa&ccedil;&otilde;es Profissionais</legend>
									<div class="col-sm-10 offset-1">
										<div>
											<p class="mb-0"><b>Divis&atilde;o: </b> {{ colaborador.divisao.full_name }}</p>
										</div>
									</div>
									<div class="col-sm-5 offset-1">
										<div>
											<p class="mb-0"><b>V&iacute;nculo: </b>{{ colaborador.vinculo }}</p>
										</div>
									</div>
									<div class="col-sm-5">
										<div>
											<p class="mb-0"><b>Colaborador Externo: </b>
												{% if colaborador.externo %}
													<img src="{% static "admin/img/icon-yes.svg" %}">
												{% else %}
													<img src="{% static "admin/img/icon-no.svg" %}">
												{% endif %}
											</p>
										</div>
									</div>
									
									<div class="col-sm-5 offset-1">
										<div>
											<p><b>Data de In&iacute;cio: </b>{{ colaborador.data_inicio|date:"SHORT_DATE_FORMAT" }}</p>
										</div>
										{% if not colaborador.externo %}
											<div>
												<p><b>Ramal: </b>{{ colaborador.ramal }}</p>
											</div>
										{% endif %}
										{% if colaborador.responsavel %}
											<div>
												<p><b>Respons&aacute;vel: </b>{{ colaborador.responsavel }}</p>
											</div>
										{% endif %}
									</div>
									<div class="col-sm-5  mt-0">
										{% if colaborador.vinculo.vinculo != 'Administrador' %}
											{% if colaborador.vinculo.vinculo == 'Servidor' %}
												<div>
													<p><b>Matr&iacute;cula SIAPE: </b>{{ colaborador.registro_inpe }}</p>
												</div>
											{% else %}
												<div>
													<p><b>Data de Fim: </b>{{ colaborador.data_fim|date:"SHORT_DATE_FORMAT" }}</p>
												</div>
											{% endif %}
										{% endif %}
										{% if not colaborador.externo %}
											<div>
												<p><b>Pr&eacute;dio: </b>{{ colaborador.predio }}</p>
											</div>
										{% endif %}
										
										{% if colaborador.vinculo.vinculo == 'Terceiro' %}
										<div>
											<p><b>Empresa Terceirizada: </b>{{ colaborador.empresa }}</p>
										</div>
										{% endif %}
									</div>
								</div>
								<div class="module-footer">
									<div class="buttons">
										<button type="button" class="btn btn-primary width-btn-min criar" id="criar"
											data-toggle="modal" data-target=".modal"
											value="{{colaborador.id}}_{{colaborador.username}}_{{colaborador.uid}}_{{colaborador.email}}">Criar
										</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% empty %}
			<div class="box-garb">
				<p>N&atilde;o existe colaborador para ser criado.</p>
			</div>
			{% endfor %}
		</div>
		<div class="box-column box-garb">
			<div class="module-header">
				<div class="legend">Colaboradores</div>
			</div>

			<div id="status"></div>
		</div>
	</div>
</div>
<div class="modal" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header alert-danger">
				<h5 class="modal-title">Criar conta no LDAP </h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form method="post" id="form_suporte_aprovar" action="{% url 'colaborador:suporte_criar_conta' 0 %}">
				<div class="modal-body">
					{% csrf_token %}
					{{  form_suporte.as_p }}
					<div class="module-footer">
						<div class="buttons">
							<button type="submit" class="btn btn-danger width-btn-min">Criar</button>
							<button type="button" class="btn btn-secondary width-btn-min"
								data-dismiss="modal">Cancelar</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

{% block extrajs %}
<script>
	$(".criar").click(function () {
		value_criar = $(this).val().split("_");
		url = "{% url 'colaborador:suporte_criar_conta' 123 %}".replace('123', value_criar[0]);
		$('#form_suporte_aprovar').attr('action', url);
		$("#id_username").attr('value', value_criar[1]);
		$("#id_uid").attr('value', value_criar[2]);
		$("#id_email").attr('value', value_criar[3]);
		$("#id_id").attr('value', value_criar[0]);
	});

	$("#status").load("{% url 'colaborador:status' %}");
</script>
{% endblock %}