portal/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from apps.colaborador.views import PasswordResetConfirmView


urlpatterns = [
    path("", TemplateView.as_view(template_name="core/home.html"), name="home"),
    path("colaborador/", include("apps.colaborador.urls.noauth")),
    path("monitoramento/", include("apps.monitoramento.urls")),
    path("conta/", include("apps.colaborador.urls.auth")),
    path("admin/administrador/", include("apps.core.urls.auth")),
    path("estrutura/", include("apps.core.urls.noauth")),
    path("infra/", include("apps.infra.urls")),
    path("biblioteca/", include("apps.biblioteca.urls")),
    path("noc/", include("apps.noc.urls")),
    path("garb/", include("garb.urls")),
    path("conta/password_reset/", auth_views.PasswordResetView.as_view(html_email_template_name="registration/password_reset_email_html.html"), name="password_reset"),
    path("conta/reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('conta/', include('django.contrib.auth.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

apps/core/models.py
import datetime

from django.contrib.auth.models import Group
from django.db import models
from apps.core.managers import ColaboradorGrupoAcessoManager, DivisaoManager, GrupoAcessoManager, GrupoTrabalhoManager, ResponsavelGrupoTrabalhoManager


class Predio(models.Model):
    predio = models.CharField("Prédio", null=True, max_length=255)
    predio_sistema = models.CharField("Abreviação", null=True, max_length=255, unique=True)
    linhas = models.IntegerField(default=0)
    colunas = models.IntegerField(default=0)
    sensores = models.IntegerField(default=0, help_text="Número de sensores no datacenter")
    areas = models.CharField("Areas neutras", max_length=255, null=True, blank=True, help_text="Conjunto de areas neutras no mapa: (1, 36, 1, 19)/(36, 43, 1, 4)/(43, 46, 1, 30)")

    class Meta:
        verbose_name = "Prédio"
        verbose_name_plural = "Prédios"
        ordering = ["predio"]

    def __str__(self):
        return self.predio

    def get_areas(self):
        areas = []
        if self.areas:
            for area in self.areas.replace("(", "").replace(")", "").split("/"):
                areas.append(area.split(","))
        return areas


class Divisao(models.Model):
    divisao = models.CharField("Divisão|Coordenação", max_length=255)
    divisao_completo = models.CharField("Nome Completo", max_length=255, null=True, blank=False)
    email = models.EmailField(null=True, max_length=255)
    coordenacao = models.CharField("Coordenação", max_length=255, null=True, blank=False)
    chefe = models.ForeignKey('colaborador.Colaborador', verbose_name="Chefe", null=True, blank=True, related_name="chefe_user", on_delete=models.PROTECT)
    chefe_ativo = models.BooleanField("Ativo", default=False, blank=True, null=True)
    chefe_substituto = models.ForeignKey('colaborador.Colaborador', verbose_name="Chefe Substituto", null=True, blank=True, related_name="chefe_user_2", on_delete=models.PROTECT)
    chefe_substituto_ativo = models.BooleanField("Ativo", default=False, blank=True, null=True)

    objects = DivisaoManager()

    class Meta:
        ordering = ["divisao"]
        verbose_name = "Divisão | Coordenação"
        verbose_name_plural = "Divisões | Coordenações"

    def __str__(self):
        return self.divisao

    @property
    def color(self):
        return "blue"
    
    @property
    def full_name(self):
        return f"{self.divisao} - {self.divisao_completo}"

    def emails_to(self):
        emails = []
        if self.chefe_ativo:
            emails.append(self.chefe.email)
        if self.chefe_substituto_ativo:
            emails.append(self.chefe_substituto.email)
        return emails


class GrupoTrabalho(models.Model):
    grupo = models.CharField("Grupo", max_length=255)
    grupo_sistema = models.CharField("Grupo no sistema", max_length=255, unique=True)
    gid = models.IntegerField(default=0)
    share = models.BooleanField("Share", default=False, blank=True, null=True)
    operacional = models.BooleanField("Operacional", default=False, blank=True, null=True)
    desenvolvimento = models.BooleanField("Desenvolvimento", default=False, blank=True, null=True)
    pesquisa = models.BooleanField("Pesquisa", default=False, blank=True, null=True)
    documento = models.BooleanField("Documento", default=False, blank=True, null=True)
    data_criado = models.DateField("Data de Criação", null=True)
    confirmacao = models.BooleanField("Confirmação de Assinatura", default=False, null=True)
    divisao = models.ForeignKey("core.Divisao", verbose_name="Divisão|Coordenação", on_delete=models.PROTECT)
    responsavel = models.ManyToManyField("colaborador.Colaborador", verbose_name="Responsável", through="ResponsavelGrupoTrabalho")
    objects = GrupoTrabalhoManager()

    class Meta:
        ordering = [
            "divisao",
            "grupo",
        ]
        verbose_name = "Grupo de Trabalho"
        verbose_name_plural = "Grupos de Trabalho"

    def __str__(self):
        return f"{self.divisao} | {self.grupo.upper()}"

    def get_sudo(self):
        return f"sudo_rules_{self.grupo_sistema}"

    def save(self, *args, **kwargs):
        self.confirmacao = False
        return super().save(*args, **kwargs)

    def save_confirm(self, *args, **kwargs):
        self.confirmacao = True
        return super().save(*args, **kwargs)


class GrupoAcesso(models.Model):
    grupo_acesso = models.CharField("Regra de Acesso", max_length=255)
    hbac_freeipa = models.CharField("HBAC no FreeIPA", max_length=255)
    tipo = models.CharField("tipo", max_length=255)
    data = models.DateTimeField(auto_now_add=True)
    grupo_trabalho = models.ForeignKey("core.GrupoTrabalho", on_delete=models.CASCADE)
    tipos = {"OPERACIONAL": "oper", "DESENVOLVIMENTO": "dev", "PESQUISA": "pesq", "DOCUMENTO": "doc"}
    objects = GrupoAcessoManager()

    class Meta:
        verbose_name = "Grupo de Acesso"
        verbose_name_plural = "Grupos de Acesso"
        ordering = [ 'grupo_trabalho',
            "grupo_acesso",
        ]

    def __str__(self):
        return self.grupo_acesso
    
    def make(self, tipo, grupo_trabalho):
        self.tipo = tipo.upper()
        self.grupo_trabalho = grupo_trabalho
        self.grupo_acesso = f"{grupo_trabalho.grupo_sistema.upper()} | {self.tipo}"
        self.hbac_freeipa = f"hbac_{grupo_trabalho.grupo_sistema}_{self.tipos[self.tipo]}"


    @property
    def description(self):
        info = self.grupo_acesso.split(" | ")
        return f"HBAC Rule de {info[1]} do Grupo {info[0]}"

    @property
    def automountmap(self):
        return f"auto.{self.grupo_trabalho.grupo_sistema}_{self.tipos[self.tipo]}"


class GrupoPortal(Group):
    class Meta:
        proxy = True
        verbose_name = "Grupo no Portal"
        verbose_name_plural = "Grupos no Portal"


class ResponsavelGrupoTrabalho(models.Model):
    responsavel = models.ForeignKey("colaborador.Colaborador", verbose_name="Responsável", on_delete=models.CASCADE)
    grupo = models.ForeignKey("core.GrupoTrabalho", on_delete=models.CASCADE)
    objects = ResponsavelGrupoTrabalhoManager()

    class Meta:
        ordering = ["responsavel"]
        verbose_name = "Responsável"
        verbose_name_plural = "Responsáveis"

    def __str__(self):
        return f"{self.responsavel.full_name} | {self.grupo.grupo}"


class ColaboradorGrupoAcesso(models.Model):
    colaborador = models.ForeignKey("colaborador.Colaborador", on_delete=models.CASCADE)
    grupo_acesso = models.ForeignKey("core.GrupoAcesso", on_delete=models.CASCADE)
    aprovacao = models.IntegerField("status", default=0)
    atualizacao = models.DateTimeField("Data de Atualização", auto_now=True, null=True)
    objects = ColaboradorGrupoAcessoManager()

    class Meta:
        ordering = ["grupo_acesso"]
        verbose_name = "Grupo de Acesso"
        verbose_name_plural = "Grupos de Acesso"
    
    def __str__(self):
        return self.grupo_acesso.grupo_acesso

    def status(self):
        if self.aprovacao == 1:
            return "Acesso Aprovado"
        return "Aguardando Aprovação"

apps/core/views.py
import datetime
from io import BytesIO
from os import remove

import xhtml2pdf.pisa as pisa
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin, PermissionRequiredMixin)
from django.contrib.staticfiles import finders
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.utils.encoding import force_text
from django.views.generic.base import RedirectView, TemplateView, View

from apps.core.models import GrupoTrabalho
from apps.colaborador.models import Colaborador
from apps.infra.models import Servidor
from apps.core.tasks import send_email_task
from apps.core.utils.freeipa import FreeIPA
from apps.core.utils.history import HistoryCore
from apps.core.utils.updategrupo import UpdateGrupoAcesso, UpdateColaboradorGrupo, UpdateGrupoVerificaDisco
from garb.views import ViewContextMixin


class AtualizarAssinaturaView(LoginRequiredMixin, PermissionRequiredMixin, View):
    template_name = "core/pdf/grupo.html"
    permission_required = "core.change_grupotrabalho"

    def get(self, request, *args, **kwargs):
        grupo = get_object_or_404(GrupoTrabalho, id=kwargs["pk"])
        responsaveis = grupo.responsavelgrupotrabalho_set.all()
        if responsaveis.count() > 0:
            context = {
                "title": "Atualizar Assinatura do Grupo",
                "logo": finders.find("image/logo.png"),
                "checkbox_on": finders.find("core/image/checkbox_on.png"),
                "checkbox_off": finders.find("core/image/checkbox_off.png"),
                "grupo": grupo,
                "responsaveis": responsaveis,
            }
            result = BytesIO()
            template = get_template(self.template_name)
            html = template.render(context)
            pisa.pisaDocument(BytesIO(html.encode("utf8")), result)
            return HttpResponse(result.getvalue(), content_type="application/pdf")
        return HttpResponse("Confirme as informações do Cadastro e/ou Responsáveis!", content_type="text/plain; charset=iso-8859-1")


class ConfirmarAssinaturaView(LoginRequiredMixin, PermissionRequiredMixin, RedirectView):
    permission_required = "core.change_grupotrabalho"

    def get_redirect_url(self, *args, **kwargs):
        grupo = get_object_or_404(GrupoTrabalho, id=kwargs["pk"])
        responsaveis_grupotrabalho = grupo.responsavelgrupotrabalho_set.all()
        if responsaveis_grupotrabalho.count() > 0:
            grupo.save_confirm()
            messages.add_message(self.request, messages.SUCCESS, "Assinatura confirmada, FreeIPA já pode ser Atualizado")
            HistoryCore(self.request).confirmar_assinatura(grupo=grupo)
            return reverse_lazy("admin:core_grupotrabalho_change", kwargs={"object_id": grupo.id})
        messages.add_message(self.request, messages.WARNING, "Confirme as informações do Cadastro e/ou Responsáveis!")
        return reverse_lazy("admin:core_grupotrabalho_change", kwargs={"object_id": grupo.id})


class CriarContaGrupoTrabalhoView(LoginRequiredMixin, PermissionRequiredMixin, RedirectView):
    permission_required = "core.change_grupotrabalho"

    def get_redirect_url(self, *args, **kwargs):
        grupo_trabalho = get_object_or_404(GrupoTrabalho, id=kwargs["pk"])
        if grupo_trabalho.responsavelgrupotrabalho_set.all().exists() and grupo_trabalho.gid > 0 and grupo_trabalho.confirmacao == True and UpdateGrupoVerificaDisco().verifica_disco(grupo_trabalho=grupo_trabalho, request=self.request):
            client_feeipa = FreeIPA(self.request)
            if client_feeipa.group_find_count(cn=grupo_trabalho.grupo_sistema) == 0:
                # Cria Conta de User Group
                if client_feeipa.set_grupo(grupo_trabalho):
                    send_email_task.delay("Conta de Grupo Criada",f"A Conta para Grupo de trabalho: {grupo_trabalho.grupo} foi criada no FreeIPA, por:{self.request.user.username,}",[settings.EMAIL_SYSADMIN])
                    # Atualiza Grupos de Acesso
                    history_core = HistoryCore(self.request)
                    history_core.update_grupo_acesso(grupo=grupo_trabalho, assunto="Nova conta de Grupo de Trabalho")
                    UpdateGrupoAcesso(client_feeipa=client_feeipa, history_core=history_core).update_acesso(grupo_trabalho)
                    UpdateColaboradorGrupo(client_feeipa=client_feeipa, history_core=history_core).update_user(grupo_trabalho)
                    messages.add_message(self.request, messages.WARNING, "Os volumes do Storage devem ser criados comforme o cadastro!")
            else:
                messages.add_message(self.request, messages.ERROR, "O grupo já existe!")
        else:
            messages.add_message(self.request, messages.ERROR, "Confira o Cadastro, existe informação faltando ou não salva! ")
        return reverse_lazy("admin:core_grupotrabalho_change", kwargs={"object_id": grupo_trabalho.id})


class AtualizarContaGrupoTrabalhoView(LoginRequiredMixin, PermissionRequiredMixin, RedirectView):
    permission_required = "core.change_grupotrabalho"

    def get_redirect_url(self, *args, **kwargs):
        grupo_trabalho = get_object_or_404(GrupoTrabalho, id=kwargs["pk"])


        if ( UpdateGrupoVerificaDisco().verifica_disco(grupo_trabalho=grupo_trabalho, request=self.request) and
        UpdateGrupoVerificaDisco().verifica_equipamento_grupoacesso(grupo_trabalho=grupo_trabalho, request=self.request)):
            client_feeipa = FreeIPA(self.request)
            history_core = HistoryCore(self.request)
            history_core.update_grupo_acesso(grupo=grupo_trabalho, assunto="Atualização da conta de Grupo de Trabalho")
            UpdateGrupoAcesso(client_feeipa=client_feeipa, history_core=history_core).update_acesso(grupo_trabalho)
            UpdateColaboradorGrupo(client_feeipa=client_feeipa, history_core=history_core).update_user(grupo_trabalho)
            messages.add_message(self.request, messages.SUCCESS, "Conta de Grupo de Trabalho Atualizada")
        return reverse_lazy("admin:core_grupotrabalho_change", kwargs={"object_id": grupo_trabalho.id})


class EstruturaGruposView(ViewContextMixin, TemplateView):
    template_name = "core/estrutura_grupos.html"
    title = "Estrutura de Grupos"

    def get_context_data(self, **kwargs):
        grupos_trabalho = GrupoTrabalho.objects.filter(data_criado__isnull=False)
        context = super(EstruturaGruposView, self).get_context_data(**kwargs)
        context["grupos"] = grupos_trabalho
        return context


class CoreStatusView(TemplateView):
    template_name = "core/status.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["colaborador"] = Colaborador.objects.values("is_active").filter(is_active=1).count()
        context["grupo"] = GrupoTrabalho.objects.values("grupo").filter(data_criado__isnull=False).count()
        context["servidor"] = Servidor.objects.values("nome").filter(status="Em uso").count()
        return context

apps/core/templates/core/estrutura_grupos.html
{% extends "admin/base.html" %}
{% load static %}
{% load i18n %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/core.css' %}"/>
{% endblock %}


{% block content %}
	<div id="content-main" >
		<div class="change-columns">
			<div class="main-column">
				<div class="box-garb">
					<div class="module-header">
						<div class="legend">Grupos de Trabalho</div>
					</div>
					<br>
                    <div class="toolbar-content">
                        <div id="toolbar">
                            <div class="search-container">
                                <div class="input-group">
                                    <input type="search"  size="40" id="search" placeholder="Procurar Grupo / Colaborador / Equipamento" >
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1"><i class="fas fa-search"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                    {% for grupo in grupos %}
                        <div  id="accordion"  class='box-garb'>
                            <div class="panel panel-default" id="heading{{ grupo.id }}">
                                <div class="panel-heading" role="tab" >
                                    <div class="module-header">
                                        <a role="button" class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ grupo.id }}" aria-expanded="false" aria-controls="collapse{{ grupo.id }}">
                                            <div class="legend">{{ grupo }}</div>
                                        </a>
                                    </div>
                                </div>
                                <div id="collapse{{ grupo.id }}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading{{ grupo.id }}">
                                    <div class="panel-body">
                                        <div class="row pt-2">
                                            <div class="col-2"></div>
                                            <div class="col-10">
                                                <div class="row p-0 m-0">
                                                    <div class="col-2 text-center  align-self-center">
                                                        <b>Respons&aacute;vel </b>
                                                    </div>
                                                    <div class="col-10 pl-0 ml-0">
                                                        {% for responsavel in grupo.responsavelgrupotrabalho_set.all %}
                                                            <div class="row m-0 p-0  ">
                                                                <div class="col-4 p-2" >
                                                                    <strong class="text-danger">{{ responsavel.responsavel.full_name }}</strong>
                                                                </div>
                                                                <div class="col-3 p-2" >
                                                                    {{ responsavel.responsavel.username }}
                                                                </div>
                                                                <div class="col-4 p-2" >
                                                                    {{ responsavel.responsavel.email }}
                                                                </div>
                                                                <div class="col-1 p-2" >
                                                                    {{ responsavel.responsavel.ramal|default:"--"}}
                                                                </div>
                                                            </div>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% for grupo_acesso in grupo.grupoacesso_set.all %}
                                            <div class="row align-items-center  border-top border-left m-0 mt-1 grupo_acesso" >
                                                <div class="col-1 text-center align-middle rotate">
                                                    <b>{{ grupo_acesso.tipo }} </b>
                                                </div>
                                                <div class="col-11">
                                                    <div class="row p-0 m-0 grupo_acesso_categoria  border-bottom">
                                                        <div class="col-12 pl-0 ml-0">
                                                            {% for colaboradorgrupoacesso in grupo_acesso.colaboradorgrupoacesso_set.all %}
                                                                {% if colaboradorgrupoacesso.aprovacao == 1 %}
                                                                    <div class="row m-0 p-0  ">
                                                                        <div class="col-4 p-2" >
                                                                            <strong class="text-primary">{{ colaboradorgrupoacesso.colaborador.full_name }}</strong>
                                                                        </div>
                                                                        <div class="col-3 p-2" >
                                                                            {{ colaboradorgrupoacesso.colaborador.username }}
                                                                        </div>
                                                                        <div class="col-4 p-2" >
                                                                            {{ colaboradorgrupoacesso.colaborador.email }}
                                                                        </div>
                                                                        <div class="col-1 p-2" >
                                                                            {{ colaboradorgrupoacesso.colaborador.ramal|default:"--"}}
                                                                        </div>
                                                                    </div>
                                                                {% endif %}
                                                            {% endfor %}
                                                        </div>
                                                    </div>
                                                    <div class="row p-0 m-0 grupo_acesso_categoria  ">
                                                        <div class="col-12 pl-0 ml-0">
                                                            {% for equipamentogrupoacesso in grupo_acesso.equipamentogrupoacesso_set.all %}
                                                                <div class="row m-0 p-0 ">
                                                                    <div class="col-2 p-2" >
                                                                        <strong class="text-primary">{{ equipamentogrupoacesso.equipamento.nome }}</strong>
                                                                    </div>
                                                                    <div class="col-2 p-2" >
                                                                        {{ equipamentogrupoacesso.equipamento.tipo }}
                                                                    </div>
                                                                    <div class="col-7 p-2" >
                                                                        {{ equipamentogrupoacesso.equipamento.descricao }}
                                                                    </div>
                                                                    <div class="col-1 p-2" >
                                                                        {{ equipamentogrupoacesso.equipamento.servidor.status }} <br>
                                                                        {{ equipamentogrupoacesso.equipamento.servidor.conta }}
                                                                    </div>
                                                                </div>
                                                            {% endfor %}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <div class="box-garb">
                            <p>N&atilde;o existe grupos de trabaho.</p>
                        </div>
                    {% endfor %}
                </div>
                <div class="box-column box-garb">
                        <div class="module-header">
                            <div class="legend">Estrutura</div>
                        </div>
                        <div id="status"></div>
                </div>
            </div>
        </div>
{% endblock %}


{% block extrajs %}
    <script>
        function collapsibleclose() {
            $('.panel-collapse.in').collapse('hide');
        }
        function filter(element) {
            searchTerm = $(element).val();
            console.log(searchTerm)
            $('#accordion > .panel ').each(function() {
                panelContainerId = '#' + $(this).attr('id');
                console.log(panelContainerId)
                
                // Makes search to be case insesitive
                $.extend($.expr[':'], {
                    'contains': function(elem, i, match, array) {
                        return (elem.textContent || elem.innerText || '').toLowerCase()
                        .indexOf((match[3] || "").toLowerCase()) >= 0;
                    }
                });
                // Show and Hide Triggers
                $(panelContainerId + ':not(:contains(' + searchTerm + '))').parent().hide();
                $(panelContainerId + ':contains(' + searchTerm + ')').parent().show();
            });
        }
        $('#search').on("keyup", function(e) {
            if( ( (e.keyCode == 8) || (e.keyCode === 27) || (e.keyCode === 46)) && ($(this).val() == '')) {
                filter(this);
                $('.panel-collapse.in').collapse('hide');
                return;
            } else if (e.keyCode === 13) {
                filter(this);
                $('.panel-collapse.in').collapse('show');
                return;
            }
        });
        $("#status").load("{% url 'core_open:status' %}");
    </script>
{% endblock %} 

apps/core/templates/core/home.html
{% extends 'admin/base.html' %}

apps/core/templates/core/status.html
<p class="p-1"><b class="pr-1">Grupos:</b> {{grupo}}</p>
<p class="p-1"><b class="pr-1">Colaboradores:</b> {{colaborador}}</p>
<p class="p-1"><b class="pr-1">Servidores:</b> {{servidor }}</p>