apps/infra/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from apps.infra.views import AlterarStatusServidorView, CriarServidorLocalView, CriarVmProgressView, CriarVmView, DataCenterJSONView, DataCenterMapView, DataCenterRackDetailView, DataCenterView, RackQRCodeView, RackDetailView, OcorrenciaNewView, RackServerDetailView, CriarServidorLdapView, DataCenterPredioView, DataCenterMapEditView

app_name = "infra"

urlpatterns = [
    path("datacenter/", DataCenterView.as_view(), name="datacenter"),
    path("datacenter/predio/<int:pk>/", DataCenterPredioView.as_view(), name="datacenter_predio"),
    path("datacenter/map/<int:pk>/", DataCenterMapView.as_view(), name="datacenter_map"),
    path("datacenter/search", DataCenterJSONView.as_view(), name="datacenter_search"),
    path("datacenter/map/edit/<int:pk>/", login_required(DataCenterMapEditView.as_view()), name="datacenter_map_edit"),
    path("datacenter/rack/detail", DataCenterRackDetailView.as_view(), name="datacenter_rack_detail"),
    path("datacenter/rack/qrcode/<int:pk>", RackQRCodeView.as_view(), name="rack_qrcode"),
    path("datacenter/rack/qrcode/<int:pk>/detail/", RackDetailView.as_view(), name="rack_detail"),
    path("datacenter/rack/server/<int:pk>/detail/", RackServerDetailView.as_view(), name="rack_server_detail"),
    path("ocorrencia/criar/", OcorrenciaNewView.as_view(), name="ocorrencia_criar"),
    path("servidor/<int:pk>/criarservidorldap/", login_required(CriarServidorLdapView.as_view()), name="criar_servidor_ldap"),
    path("servidor/<int:pk>/alterarstatus/", login_required(AlterarStatusServidorView.as_view()), name="alterar_servidor_status"),
    path("servidor/<int:pk>/criarservidorlocal/", login_required(CriarServidorLocalView.as_view()), name="criar_servidor_local"),
    path("servidor/<int:pk>/criarVM/", login_required(CriarVmView.as_view()), name="criar_vm"),
    path("servidor/<int:pk>/<template_id>/<task_id>/criarVM/progress", login_required(CriarVmProgressView.as_view()), name="criar_vm_progress"),
]

portal/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from apps.colaborador.views import PasswordResetConfirmView


urlpatterns = [
    path("", TemplateView.as_view(template_name="core/home.html"), name="home"),
    path("colaborador/", include("apps.colaborador.urls.noauth")),
    path("monitoramento/", include("apps.monitoramento.urls")),
    path("conta/", include("apps.colaborador.urls.auth")),
    path("admin/administrador/", include("apps.core.urls.auth")),
    path("estrutura/", include("apps.core.urls.noauth")),
    path("infra/", include("apps.infra.urls")),
    path("biblioteca/", include("apps.biblioteca.urls")),
    path("noc/", include("apps.noc.urls")),
    path("garb/", include("garb.urls")),
    path("conta/password_reset/", auth_views.PasswordResetView.as_view(html_email_template_name="registration/password_reset_email_html.html"), name="password_reset"),
    path("conta/reset/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('conta/', include('django.contrib.auth.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    path('notifications/', include('django_nyt.urls')),
    path('wiki/', include('wiki.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns

apps/infra/views.py
import base64
import io
import json
from itertools import chain

import pyqrcode
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView
from django.views.generic.base import RedirectView, TemplateView
from django.views.generic.edit import CreateView, FormView
from garb.views import ViewContextMixin

from apps.core.models import Predio
from apps.core.tasks import send_email_task
from apps.core.utils.freeipa import FreeIPA
from apps.infra.forms import OcorrenciaForm, ServidorVMForm
from apps.infra.models import (LINHAS, Equipamento, EquipamentoParte,
                               Ocorrencia, Rack, Servidor, TemplateVM)
from apps.infra.utils.datacenter import DataCenterMap, RackMap
from apps.infra.utils.freeipa_location import Automount
from apps.infra.utils.history import HistoryInfra
from apps.infra.utils.xen_crud import XenCrud
from apps.monitoramento.models.nagios import NagiosServicos


class DataCenterView(ViewContextMixin, TemplateView):
    template_name = "infra/datacenter/datacenter.html"
    title = 'Monitoramento Datacenter'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["predios"] = Predio.objects.all().filter(linhas__isnull=False, colunas__isnull=False,)
        return context

class DataCenterPredioView(TemplateView):
    template_name = "infra/datacenter/datacenter_predio.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        predio = get_object_or_404(Predio, id=kwargs["pk"])
        datacenter_map = DataCenterMap(predio)
        context["quantidade_racks"] = Rack.objects.filter(predio=predio).count()
        context["quantidade_equipamentos"] = Equipamento.objects.filter(predio=predio).filter(Q(tipo='Servidor Físico') | Q(tipo='Equipamento Físico')).count()
        context["matriz_datacenter"] = datacenter_map.draw_datacenter(sensor=True)
        context["sensores"] = datacenter_map.sensores
        context["title"] = predio.predio
        return context


class DataCenterMapView(TemplateView):
    template_name = "infra/datacenter/datacenter_map.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        predio = get_object_or_404(Predio, id=kwargs["pk"])
        datacenter = DataCenterMap(predio)
        context["matriz_datacenter"] = datacenter.draw_datacenter()
        return context


class DataCenterMapEditView(TemplateView):
    template_name = "infra/datacenter/datacenter_map.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rack = get_object_or_404(Rack, id=kwargs["pk"])
        datacenter = DataCenterMap(rack.predio, id_rack=rack.pk)
        context["matriz_datacenter"] = datacenter.draw_datacenter()
        return context


class DataCenterJSONView(TemplateView):
    search = None
    racks_id_templates = []

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        self.search = request.GET.get("search", None).lower()
        return self.render_to_response(context)

    def render_to_response(self, context, **response_kwargs):
        if self.search:
            servidores = chain(Servidor.objects.filter(nome__contains=str(self.search)), EquipamentoParte.objects.filter(marca__icontains=str(self.search)), EquipamentoParte.objects.filter(modelo__icontains=str(self.search)))
            self.racks_id_templates = [f'div[data-element="#rack_{str(x.rack.id)}"]' for x in servidores if x.rack is not None ]
        return HttpResponse(json.dumps(list(dict.fromkeys(self.racks_id_templates))), content_type="application/json")


class DataCenterRackDetailView(TemplateView):
    template_name = "infra/datacenter/rack_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rack = RackMap(self.request.GET.get("pk", None), self.request.GET.get("search", None).lower())
        context["rack"] = rack.draw_rack()
        return context


class RackQRCodeView(DetailView):
    model = Rack
    template_name = "infra/rack/qrcode.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qrcode = pyqrcode.create(self.request.scheme + "://" + self.request.get_host() + reverse("infra:rack_detail", args=[context["rack"].id]))
        file = io.BytesIO()
        qrcode.png(file, scale=6)
        context["qrcode"] = base64.b64encode(file.getvalue()).decode("ascii")
        return context


class RackDetailView(DetailView):
    model = Rack
    template_name = "infra/rack/rack_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rack = RackMap(context["rack"].id, None)
        context["rack"] = rack.draw_rack()
        return context


class RackServerDetailView(DetailView):
    model = Equipamento
    template_name = "infra/rack/rack_server_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form_ocorrencia"] = OcorrenciaForm(initial={"equipamento": self.get_object()})
        return context


class OcorrenciaNewView(CreateView):
    model = Ocorrencia
    form_class = OcorrenciaForm
    template_name = "infra/rack/rack_server_detail.html"
    rack_id = 0

    def form_valid(self, form):
        ocorrencia = form.save(commit=False)
        self.rack_id = ocorrencia.equipamento.rack.id
        return super(OcorrenciaNewView, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse_lazy("infra:rack_detail", kwargs={"pk": self.rack_id})


class CriarServidorLdapView(LoginRequiredMixin, PermissionRequiredMixin, RedirectView):
    permission_required = "infra.change_servidor"

    def get_redirect_url(self, *args, **kwargs):
        servidor = get_object_or_404(Servidor, id=kwargs["pk"])
        grupos_acesso = servidor.grupos_acesso.all()
        if grupos_acesso.exists() and servidor.conta == "Aguardando":
            client_feeipa = FreeIPA(self.request)
            if client_feeipa.set_host(servidor, description=servidor.descricao):
                automount = Automount(client_feeipa, servidor, self.request)
                automount.adicionar_grupos(grupos_acesso)
                automount.adicionar_oper()
                automount.adicionar_home()
                HistoryInfra(self.request).novo_servidor(servidor=servidor)
                send_email_task.delay("Servidor Criado",f"O Servidor: {servidor.nome} foi criado no FreeIPA, por:{self.request.user.username}",[settings.EMAIL_SYSADMIN])
                servidor.conta = "FreeIPA"
                servidor.save()
                messages.add_message(self.request, messages.WARNING, "Verifique as regras de export do storage!")
                if servidor.tipo == 'Servidor Virtual':
                    return reverse_lazy("infra:criar_vm", kwargs={"pk": servidor.id, })
        else:
            messages.add_message(self.request, messages.ERROR, "Confira o Cadastro, existe informação faltando ou não salva! É necessário um grupo de acesso! ")
        return reverse_lazy("admin:infra_servidor_change", kwargs={"object_id": servidor.id, })


class CriarServidorLocalView(LoginRequiredMixin, PermissionRequiredMixin, RedirectView):
    permission_required = "infra.change_servidor"

    def get_redirect_url(self, *args, **kwargs):
        servidor = get_object_or_404(Servidor, id=kwargs["pk"])
        grupos_acesso = servidor.grupos_acesso.all()
        if grupos_acesso.exists() and servidor.conta == "Aguardando":
            HistoryInfra(self.request).novo_servidor(servidor=servidor)
            send_email_task.delay("Servidor Criado",f"O Servidor: {servidor.nome} foi criado com conta Local, por:{self.request.user.username}",[settings.EMAIL_SYSADMIN])
            servidor.conta = "Local"
            servidor.save()
            if servidor.tipo == 'Servidor Virtual':
                return reverse_lazy("infra:criar_vm", kwargs={"pk": servidor.id, })
        else:
            messages.add_message(self.request, messages.ERROR, "Confira o Cadastro, existe informação faltando ou não salva! É necessário um grupo de acesso! ")
        return reverse_lazy("admin:infra_servidor_change", kwargs={"object_id": servidor.id, })

class AlterarStatusServidorView(LoginRequiredMixin, PermissionRequiredMixin, RedirectView):
    permission_required = "infra.view_servidor"

    def get_redirect_url(self, *args, **kwargs):
        servidor = get_object_or_404(Servidor, id=kwargs["pk"])
        if servidor.status == "Manutenção":
            servidor.status = "Em uso"
            nagios_servicos = NagiosServicos.objects.all().filter(padrao=True)
            servidor_nagios_servicos = servidor.nagios_servicos.all()
            [servidor.nagios_servicos.add(servico) for servico in nagios_servicos if servico not in servidor_nagios_servicos]
            servidor.save()
        else:
            servidor.status = "Manutenção"
            servidor.save()

        messages.add_message(self.request, messages.SUCCESS, "Status do Servidor Alterado!")
        HistoryInfra(self.request).status_servidor(servidor=servidor)
        send_email_task.delay("Mudança de Status do Servidor",f"O Servidor: {servidor.nome} teve seu status alterado para: {servidor.status} por:{self.request.user.username}",[settings.EMAIL_SYSADMIN, settings.EMAIL_SUPORTE])
        return reverse_lazy("admin:infra_servidor_change", kwargs={"object_id": servidor.id, })



class CriarVmView(LoginRequiredMixin, PermissionRequiredMixin, FormView):

apps/infra/templates/infra/datacenter/datacenter.html
{% extends "admin/base.html" %}

{% block content %}
<div id="content-main">
    <div class="change-columns">
        <div class="main-column">
            <div class="main-column-item">
                <br>
                {% for predio in predios %}
                <div class="box-garb p-0 box-garb-hover">
                    <div class="panel panel-default ">
                        <div class="panel-heading" role="tab">
                            <h4 class="panel-title m-0 ">
                                <a role="button" class="d-block w-100 p-4" href="{% url 'infra:datacenter_predio' predio.id %}">
                                    Datacenter: {{ predio.predio }}
                                </a>
                            </h4>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock %}

apps/infra/templates/infra/datacenter/datacenter_map.html
{% load i18n static %}
{% load templatetags %}
{{ block.super }}

<table class="table-datacenter">
    <tbody>
        {% for linha in matriz_datacenter %}
            {% with index=forloop.counter0 %}
            <tr>
                {% for cell in linha reversed %}
                    {% if cell.index_coluna %}
                        <th class="text-center index-color align-middle col_{{ cell.index_coluna }} " scope="col">{{ cell.index_coluna }}</th>
                    {% elif cell.index_linha %}
                        <th class="text-center index-color align-middle linha " scope="row" id="{{ cell.index_linha }}">{{ cell.index_linha|upper }}</th>
                    {% else %}
                        <td class="col_{{ forloop.revcounter0 }} index_{{ index }} {{ cell.edit }}">
                            {% if cell.rack %}
                                <div class="rack {{ cell.rack }} {{ cell.border }}" data-select="true" data-element="#rack_{{ cell.rack }}" data-name="{{ cell.rack }}">
                                    {% if cell.name %} {{cell.name}} {% endif %}
                                </div>
                            {% endif %}
                            {% if cell.area %}
                                <div class="area {{ cell.area }}"></div>
                            {% endif %}
                            {% if cell.escala %}
                                <div style="background-color:{{cell.escala}}" class="area_sensor" data-toggle="tooltip" data-placement="top" data-html="true" title="{{cell.temperatura}}&#186;"></div>
                            {% endif %}
                        </td>
                    {% endif %}
                {% endfor %}
            </tr>
            {% endwith %}
        {% endfor %}
    </tbody>
</table> 

apps/infra/templates/infra/datacenter/datacenter_predio.html
{% extends "admin/base.html" %}
{% load i18n static  %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'infra/css/dataCenter.css' %}">
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <ul class="breadcrumb {{ align }}">
            <li>
                <a href="{% url 'infra:datacenter' %}">MONITORAMENTO DATACENTER</a>
                <span class="divider">/</span>
            </li>
            <li class="active">
                {{title}}
            </li>
        </ul>
    </div>
{% endblock %}


{% block content %}
    <div class="content" id='datacenter_sensor'>
        <div class="row m-0">
            <div class="col-2 p-1">
                <div class="card shadow-menu blue-grey lighten-5">
                    <p class="p-2 pr-4 m-0">Racks: <b class="float-right">{{ quantidade_racks }}</b></p>
                </div>
            </div>
            <div class="col-2 p-1">
                <div class="card shadow-menu blue-grey lighten-5">
                    <p class="p-2 pr-4 m-0">Equipamentos: <b class="float-right">{{ quantidade_equipamentos }}</b></p>
                </div>
            </div>
            <div class="col-2 p-1"></div>

            <div class="col-4 p-1 ">
                <div class="toolbar-content p-0 ">
                    <div id="toolbar">
                        <div class="search-container">
                            <div class="input-group">
                                <input type="search"  size="40" id="search" placeholder="Procurar equipamento" class='mr-0' >
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1"><i class="fas fa-search"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-2 p-1">
                <button type="button" class="button float-right" id="view_monitoramento" data-name="view_datacenter">
                    <i class="fa fa-eye fa-lg p-1"></i>
                </button>
            </div>
        </div>
        <div class="row m-0 p-1" >
                <div class="col-10 p-2 d-flex justify-content-center border rounded ">
                    {% include "./datacenter_map.html" %}
                </div>
                <div class="col-2 m-0 p-1">
                    <div class="row p-0 m-0">
                        {% if sensores %}
                            <div class="col-12 h5 pt-2 text-center "> SENSORES</div>
                            {% for sensor in sensores %}
                                {% if sensor.tipo == "M" %}
                                    <div class="col-6 p-0 m-0  mb-1 pl-1 sensor" data-name=".col_{{ sensor.get_col }}.index_{{ sensor.get_index }} div" >
                                        <div class="card shadow-menu border-0">
                                            <div class="card-body  black-text {{ sensor.get_status }} darken-4 m-0 card-grupo-numero  card-body-sensor ">
                                                <h5 class="card-title p-1 pt-0 m-0  text-white">{{ sensor}}</h5>
                                                <div class="card-text p-0 pr-0  {{ sensor.get_status }} lighten-2 card-grupo-data">
                                                    <div class="row p-0 pt-1 m-0 sensor-info">
                                                        <div class="col-6 p-1"> <i class="fa fa-temperature-low  infoi "></i>&nbsp;<b>{{ sensor.temperatura }}&#186;</b></div>
                                                        <div class="col-6 p-1"> <i class="fa fa-tint infoi"></i>&nbsp;<b>{{ sensor.umidade }}%</b></div>
                                                        <div class="col-12 p-1"> <i class="fa fa-clock  infoi "></i>&nbsp;{{ sensor.atualizacao|date:"d/m H:i" }} </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
        </div> 
    </div>

    <div class="modal fade" id="rack_detail" tabindex="-1" role="dialog" aria-labelledby="rack_detailabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" id="rack_detail_content"> </div>
    </div>
{% endblock %}

{% block extrajs %}
    <script src="{% static 'js/garb_page_wide.js' %}"></script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip({ boundary: 'window' })
        })
    </script>
    <script>
        $(".rack").click(function (e) {
            $("div.rack").removeClass("blue darken-4");
            var rack = $(this).attr('data-name')
            $(".rack."+rack).addClass("blue darken-4");
            $.ajax({
                url: "{% url 'infra:datacenter_rack_detail' %}",
                data: ({ 'pk': $(this).attr('data-name'), 'search': $('#search').val()}),
                type: "GET",
                success: function (data) {
                    $("#rack_detail_content").html(data)
                    $('#rack_detail').modal('show')
                },
            });
        });
        $('#rack_detail').on('hidden.bs.modal', function () {
            $("div.rack").removeClass("blue darken-4");
            $('div.rack').removeClass("green darken-4")
            $('#search').val("")
        })
        $('#search').on("keyup", function (e) {
            $('#rack_detail').modal('hide')
            $('div.rack').removeClass("blue darken-4")
            $('div.rack').removeClass("green darken-4")
            if ((e.keyCode === 13) && ($(this).val() !== '')) {
                $.ajax({
                    dataType: "json",
                    url: "{% url 'infra:datacenter_search' %}",
                    data: ({ 'search': $(this).val() }),
                    type: "GET",
                    success: function (data) {
                        $.each(data, function (index) {
                            $(data[index]).addClass("green darken-4");
                        });
                    },
                });
                return;
            }
        });

        $(".sensor").hover(function(){
            $($(this).attr('data-name')).toggleClass(" red accent-4 ");
        });

        setInterval(function () { window.location.reload(); }, 180000);
    </script>
{% endblock %}

apps/infra/templates/infra/datacenter/rack_detail.html
    <div class="modal-content">
        <div class="modal-header blue darken-4 p-1">
            <h5 class="modal-title text-center text-white font-weight-bold w-100" id="exampleModalLabel">RACK {{ rack.rack|cut:" " }}</h5>
            <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body p-1">
            <div class="row m-0 rack_border_color ">
                <div class="col-1 m-0 p-0 rack_position_col ">
                    {% for posicao in  rack.posicoes %}
                        <div class="rack_detail rack_position align-middle">{{ posicao }}</div>
                    {% endfor %}
                </div>
                <div class="col-5 m-0 p-0 rack_detail_col">
                    {% for posicao in rack.equipamentos %}
                        {% if posicao.equipamento %}
                            <div class="rack_detail rack_server_color  rack-t{{posicao.equipamento.rack_tamanho}} align-middle {{posicao.search}}" 
                                data-toggle="tooltip" data-placement="right" data-html="true" title="<p><br>Nome: <b>{{posicao.equipamento.nome}}</b><br><br>Tipo: <b>{{ posicao.equipamento.tipo }}</b><br>Descrição: <b>{{ posicao.equipamento.descricao }}</b><br>Grupo: <b>{{ posicao.equipamento.grupo_acesso_name }}</b><br>Tipo: <b>{{ posicao.equipamento.tipo_uso }}</b><br><br>Marca: <b>{{ posicao.equipamento.marca }}</b><br>Modelo: <b>{{ posicao.equipamento.modelo }}</b><br>Patrimônio: <b>{{ posicao.equipamento.patrimonio }}</b><br>Serial: <b>{{ posicao.equipamento.serie }}</b><br>Garantia: <b>{{ posicao.equipamento.garantia }}</b><br>Consumo: <b>{{ posicao.equipamento.consumo|default:"--" }} watts</b> </p>"
                            >
                                <div class="equipamento_nome text-white"> {{ posicao.equipamento.nome }}</div>
                                {% for ocorrencia in posicao.equipamento.ocorrencia_set.all %}
                                    <div class="alerta {{ ocorrencia.get_status }}"></div>
                                {% endfor %}
                            </div>
                        {% elif posicao.kvm %}
                            <div class="rack_detail rack_kvm_color rack_kvm">KVM</div>
                        {% else %}
                            {% if not posicao.continuacao %}
                                <div class="rack_detail rack_closed_espace_color">{{posicao.continuacao}}</div>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="col-6 m-0 p-0 white  pb-1 pl-1 rack_detail_detail">
                    <div class="card">
                        <div class="card-body grey lighten-4">
                            Marca: <b>{{ rack.marca }}</b> <br>
                            Modelo: <b>{{ rack.modelo }}</b> <br>
                            Patrimônio: <b>{{ rack.patrimonio }}</b> <br><br>
                            Limite: <b>{{ rack.consumo|default:"--" }}<small> watts</small></b> <br>
                            Disponível: <b>{{ rack.disponivel|default:"--"  }}<small> watts</small></b> <br>
                            Primeiro PDU: <b>{{ rack.pdu1|default:"--" }}</b><br>
                            Segundo PDU: <b>{{ rack.pdu2|default:"--" }}</b>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip({ boundary: 'window' })
    })
</script>